[package]
name = "solar-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
approx = "0.5"

[lib]
name = "solar_core"
path = "src/lib.rs"
